name: Trigger DalamudPlugins

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Regenerate PluginMaster
        run: |
          curl -fsSL -X POST \
            -H "Authorization: Bearer ${{ secrets.DALAMUD_PLUGINS_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/44451516-ff14/DalamudPlugins/actions/workflows/main.yml/dispatches \
            -d '{"ref":"master"}'
